version: 2
jobs:
  build:
    docker:
      - image: hairyhenderson/gomplate-ci-build:latest
    environment:
      - CIRCLE_TEST_REPORTS: /tmp/test-results
    working_directory: /go/src/github.com/hairyhenderson/gomplate
    steps:
      - checkout
      - run: make build
      - run:
          name: Unit Tests
          command: |
            set -e
            set -o pipefail
            make test | go-junit-report > $CIRCLE_TEST_REPORTS/report.xml
      - run: gometalinter -j 1 --vendor --deadline 70s --disable gotype --enable gofmt --enable goimports --enable misspell --enable unused --disable gas
      - run: make test-integration
      - store_artifacts:
          path: bin
          destination: binaries
      - store_test_results:
          path: /tmp/test-results
