FROM vault:1.5.4 AS vault

FROM consul:1.8.5 AS consul

FROM golang:1.15.5-alpine3.12

COPY --from=vault /bin/vault /bin/vault
COPY --from=consul /bin/consul /bin/consul

RUN apk add --no-cache make tzdata

WORKDIR /go/src/github.com/hairyhenderson/gomplate/
COPY internal/tests/integration ./internal/tests/integration
COPY Makefile ./Makefile
COPY bin/gomplate_linux-amd64 ./bin/gomplate

CMD ["make", "integration"]
