FROM vault:1.3.1 AS vault

FROM consul:1.6.2 AS consul

FROM golang:1.13.6-alpine

COPY --from=vault /bin/vault /bin/vault
COPY --from=consul /bin/consul /bin/consul

RUN apk add --no-cache make tzdata

WORKDIR /go/src/github.com/hairyhenderson/gomplate/
COPY tests/integration ./tests/integration
COPY Makefile ./Makefile
COPY bin/gomplate_linux-amd64 ./bin/gomplate

CMD ["make", "integration"]
