#!/bin/bash
set -exuo pipefail

docker version

echo "======== Build hook running"
export BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
export VCS_REF=`git rev-parse --short HEAD`
export DOCKER_REPO=${DOCKER_REPO:-hairyhenderson/gomplate}
export DOCKER_TAG=${DOCKER_TAG:-latest}
export IMAGE_NAME=${IMAGE_NAME:-${DOCKER_REPO}:${DOCKER_TAG}}

docker build --target artifacts \
             -t ${DOCKER_REPO}:artifacts .

echo "======== Building $IMAGE_NAME"
docker build --build-arg BUILD_DATE \
             --build-arg VCS_REF \
             --target gomplate \
             -t ${IMAGE_NAME} .

if [ "$DOCKER_TAG" == "latest" ]; then
  export SLIM_TAG="slim"
else
  export SLIM_TAG="${DOCKER_TAG}-slim"
fi
echo "======== Building ${DOCKER_REPO}:${SLIM_TAG}"
docker build --build-arg BUILD_DATE \
             --build-arg VCS_REF \
             --target gomplate-slim \
             -t ${DOCKER_REPO}:${SLIM_TAG} .

if [ "$DOCKER_TAG" == "latest" ]; then
  export ALPINE_TAG="alpine"
else
  export ALPINE_TAG="${DOCKER_TAG}-alpine"
fi
echo "======== Building ${DOCKER_REPO}:${ALPINE_TAG}"
docker build --build-arg BUILD_DATE \
             --build-arg VCS_REF \
             --target gomplate-alpine \
             -t ${DOCKER_REPO}:${ALPINE_TAG} .
