#!/bin/bash

# This magic figures out if we're currently on a tag (i.e. a release).
# We only want to have special tags for releases.
if (git describe --abbrev=0 --exact-match &>/dev/null); then
  tag=$(git describe --abbrev=0 --exact-match)
  docker tag $IMAGE_NAME $DOCKER_REPO:$tag
  docker tag $IMAGE_NAME:slim $DOCKER_REPO:$tag-slim
  docker push $DOCKER_REPO
fi
