// Code generated by gencel. DO NOT EDIT.

package funcs

import "github.com/google/cel-go/cel"
import "github.com/google/cel-go/common/types"
import "github.com/google/cel-go/common/types/ref"

var dataJSONGen = cel.Function("data.JSON",
	cel.Overload("data.JSON_interface{}",

		[]*cel.Type{
			cel.DynType,
		},
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x DataFuncs

			a0, a1 := x.JSON(args[0])
			return types.DefaultTypeAdapter.NativeToValue([]any{
				a0, a1,
			})

		}),
	),
)

var dataJSONArrayGen = cel.Function("data.JSONArray",
	cel.Overload("data.JSONArray_interface{}",

		[]*cel.Type{
			cel.DynType,
		},
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x DataFuncs

			a0, a1 := x.JSONArray(args[0])
			return types.DefaultTypeAdapter.NativeToValue([]any{
				a0, a1,
			})

		}),
	),
)

var dataYAMLGen = cel.Function("data.YAML",
	cel.Overload("data.YAML_interface{}",

		[]*cel.Type{
			cel.DynType,
		},
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x DataFuncs

			a0, a1 := x.YAML(args[0])
			return types.DefaultTypeAdapter.NativeToValue([]any{
				a0, a1,
			})

		}),
	),
)

var dataYAMLArrayGen = cel.Function("data.YAMLArray",
	cel.Overload("data.YAMLArray_interface{}",

		[]*cel.Type{
			cel.DynType,
		},
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x DataFuncs

			a0, a1 := x.YAMLArray(args[0])
			return types.DefaultTypeAdapter.NativeToValue([]any{
				a0, a1,
			})

		}),
	),
)

var dataTOMLGen = cel.Function("data.TOML",
	cel.Overload("data.TOML_interface{}",

		[]*cel.Type{
			cel.DynType,
		},
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x DataFuncs

			a0, a1 := x.TOML(args[0])
			return types.DefaultTypeAdapter.NativeToValue([]any{
				a0, a1,
			})

		}),
	),
)

var dataCSVGen = cel.Function("data.CSV",
	cel.Overload("data.CSV_string",

		[]*cel.Type{
			cel.DynType,
		},
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x DataFuncs
			list := transferSlice[string](args[0].(ref.Val))

			a0, a1 := x.CSV(list...)
			return types.DefaultTypeAdapter.NativeToValue([]any{
				a0, a1,
			})

		}),
	),
)

var dataCSVByRowGen = cel.Function("data.CSVByRow",
	cel.Overload("data.CSVByRow_string",

		[]*cel.Type{
			cel.DynType,
		},
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x DataFuncs
			list := transferSlice[string](args[0].(ref.Val))

			a0, a1 := x.CSVByRow(list...)
			return types.DefaultTypeAdapter.NativeToValue([]any{
				a0, a1,
			})

		}),
	),
)

var dataCSVByColumnGen = cel.Function("data.CSVByColumn",
	cel.Overload("data.CSVByColumn_string",

		[]*cel.Type{
			cel.DynType,
		},
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x DataFuncs
			list := transferSlice[string](args[0].(ref.Val))

			a0, a1 := x.CSVByColumn(list...)
			return types.DefaultTypeAdapter.NativeToValue([]any{
				a0, a1,
			})

		}),
	),
)

var dataToCSVGen = cel.Function("data.ToCSV",
	cel.Overload("data.ToCSV_interface{}",

		[]*cel.Type{
			cel.DynType,
		},
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x DataFuncs
			list := transferSlice[interface{}](args[0].(ref.Val))

			a0, a1 := x.ToCSV(list...)
			return types.DefaultTypeAdapter.NativeToValue([]any{
				a0, a1,
			})

		}),
	),
)

var dataToJSONGen = cel.Function("data.ToJSON",
	cel.Overload("data.ToJSON_interface{}",

		[]*cel.Type{
			cel.DynType,
		},
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x DataFuncs

			a0, a1 := x.ToJSON(args[0])
			return types.DefaultTypeAdapter.NativeToValue([]any{
				a0, a1,
			})

		}),
	),
)

var dataToJSONPrettyGen = cel.Function("data.ToJSONPretty",
	cel.Overload("data.ToJSONPretty_string_interface{}",

		[]*cel.Type{
			cel.StringType, cel.DynType,
		},
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x DataFuncs

			a0, a1 := x.ToJSONPretty(args[0].Value().(string), args[1])
			return types.DefaultTypeAdapter.NativeToValue([]any{
				a0, a1,
			})

		}),
	),
)

var dataToYAMLGen = cel.Function("data.ToYAML",
	cel.Overload("data.ToYAML_interface{}",

		[]*cel.Type{
			cel.DynType,
		},
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x DataFuncs

			a0, a1 := x.ToYAML(args[0])
			return types.DefaultTypeAdapter.NativeToValue([]any{
				a0, a1,
			})

		}),
	),
)

var dataToTOMLGen = cel.Function("data.ToTOML",
	cel.Overload("data.ToTOML_interface{}",

		[]*cel.Type{
			cel.DynType,
		},
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x DataFuncs

			a0, a1 := x.ToTOML(args[0])
			return types.DefaultTypeAdapter.NativeToValue([]any{
				a0, a1,
			})

		}),
	),
)
