// Code generated by gencel. DO NOT EDIT.

package funcs

import "github.com/google/cel-go/cel"
import "github.com/google/cel-go/common/types"
import "github.com/google/cel-go/common/types/ref"

var uuidV1Gen = cel.Function("uuid.V1",
	cel.Overload("uuid.V1_",
		nil,
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x UUIDFuncs

			a0, a1 := x.V1()
			return types.DefaultTypeAdapter.NativeToValue([]any{
				a0, a1,
			})

		}),
	),
)

var uuidV4Gen = cel.Function("uuid.V4",
	cel.Overload("uuid.V4_",
		nil,
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x UUIDFuncs

			a0, a1 := x.V4()
			return types.DefaultTypeAdapter.NativeToValue([]any{
				a0, a1,
			})

		}),
	),
)

var uuidNilGen = cel.Function("uuid.Nil",
	cel.Overload("uuid.Nil_",
		nil,
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x UUIDFuncs

			a0, a1 := x.Nil()
			return types.DefaultTypeAdapter.NativeToValue([]any{
				a0, a1,
			})

		}),
	),
)

var uuidIsValidGen = cel.Function("uuid.IsValid",
	cel.Overload("uuid.IsValid_interface{}",

		[]*cel.Type{
			cel.DynType,
		},
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x UUIDFuncs

			a0, a1 := x.IsValid(args[0])
			return types.DefaultTypeAdapter.NativeToValue([]any{
				a0, a1,
			})

		}),
	),
)

var uuidParseGen = cel.Function("uuid.Parse",
	cel.Overload("uuid.Parse_interface{}",

		[]*cel.Type{
			cel.DynType,
		},
		cel.DynType,
		cel.FunctionBinding(func(args ...ref.Val) ref.Val {

			var x UUIDFuncs

			a0, a1 := x.Parse(args[0])
			return types.DefaultTypeAdapter.NativeToValue([]any{
				a0, a1,
			})

		}),
	),
)
