name: Build
on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux-build:
    runs-on: ${{ matrix.runner }}
    container:
      image: ghcr.io/hairyhenderson/gomplate-ci-build@sha256:79d444422ee6ce2e762ab7b34891d7e91b2773aa3fed7bf56a25b3eb9853adfb
    strategy:
      fail-fast: false
      matrix:
        include:
          - goarch: '386'
            runner: ubuntu-latest
          - goarch: 'amd64'
            runner: ubuntu-latest
          - goarch: 'arm'
            goarm: '7'
            runner: ubuntu-24.04-arm
          - goarch: 'arm64'
            runner: ubuntu-24.04-arm
    steps:
      - run: |
          git config --global user.email "bogus@example.com"
          git config --global user.name "Someone"
          git config --global --add safe.directory /__w/gomplate/gomplate
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-${{ runner.arch }}-${{ matrix.goarch }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-${{ matrix.goarch }}-go-
      - run: make build GOARCH=${{ matrix.goarch }} GOARM=${{ matrix.goarm }}
      - run: make test GOARCH=${{ matrix.goarch }} GOARM=${{ matrix.goarm }}
      - name: Check schema is up to date
        if: matrix.goarch == 'amd64'
        run: make -B schema/gomplate-config.json && git diff --exit-code schema/
      - run: make integration GOARCH=${{ matrix.goarch }} GOARM=${{ matrix.goarm }}
  windows-build:
    runs-on: windows-latest
    env:
      # note: the tmp dir is set to C: so that it's not on the same drive as the
      # repo, which is on D: - this will expose bugs with path handling!
      TMP: C:\tmp
    steps:
      - run: pwd
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: go.mod
      - run: |
          git config --global user.email "bogus@example.com"
          git config --global user.name "Someone"
      - run: make build
      - run: make test
      - run: make integration
